### ISSUE TITLE
 CyberPanel WHMCS Module auto create account problem

### ISSUE THREAD

**Issue by navaslord** [jetchirag/cyberpanel-whmcs#10]
I can create account with the module, I using only Numbers and Letters, and still the issue.

![image](https://user-images.githubusercontent.com/2480263/207090042-562a3f21-d385-4e3c-8abb-0741eebd8290.png)

**Comment by altomarketing** [comment]
check if your user you configured in whmcs , has api access

**Comment by jetchirag** [comment]
Closing due to being stale.
