### ISSUE TITLE
Auto login option is not available in WHMCS client area

### ISSUE THREAD

**Issue by mtdas99** [jetchirag/cyberpanel-whmcs#2]
1. User created, package assigned but the client is not able to login to Cyberpanel as the Username is showing as **root** on welcome email. The actual username created on Cyberpanel is not available anywhere for the Client. Also My Products & services under Client area has no option for auto login to the Cyberpanel as user. Is there any codings available to show "Login to Server/Cyberpanel" button at My products & services under client area?

2. When clicking on the purchased product at Clent area it shows below error:

Error: Call to a member function setUri() on null in /home/hostingskull.com/billing.hostingskull.com/includes/hooks/a.php:14
Stack trace:
#0 /home/hostingskull.com/billing.hostingskull.com/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): WHMCS\Utility\SafeInclude::{closure}()
#1 /home/hostingskull.com/billing.hostingskull.com/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run()
#2 /home/hostingskull.com/billing.hostingskull.com/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic()
#3 /home/hostingskull.com/billing.hostingskull.com/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): run_hook()
#4 /home/hostingskull.com/billing.hostingskull.com/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->outputWithoutExit()
#5 /home/hostingskull.com/billing.hostingskull.com/vendor/whmcs/whmcs-foundation/lib/Http/Message/AbstractViewableResponse.php(0): WHMCS\ClientArea->getOutputContent()
#6 /home/hostingskull.com/billing.hostingskull.com/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(41): WHMCS\Http\Message\AbstractViewableResponse->getBody()
#7 /home/hostingskull.com/billing.hostingskull.com/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(31): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emitBody()
#8 /home/hostingskull.com/billing.hostingskull.com/clientarea.php(0): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit()
#9 {main}

Codes available on /home/hostingskull.com/billing.hostingskull.com/includes/hooks/a.php:

`<?php

use WHMCS\View\Menu\Item as MenuItem;

add_hook('ClientAreaPrimarySidebar', 1, function(MenuItem $primarySidebar)
{

$service = Menu::context('service');    
$domain = $service->domain;

if (!is_null($primarySidebar->getChild('Service Details Actions'))) {
            $primarySidebar->getChild('Service Details Actions')
                           ->getChild('Login to cPanel')
                           ->setUri('http://cpanel.'.$domain);
            $primarySidebar->getChild('Service Details Actions')
                           ->getChild('Login to Webmail')
                           ->setUri('http://webmail.'.$domain);
   }
});
`

**Comment by jetchirag** [comment]
Well, the username should definitely match on cyberpanel and whmcs. Which WHMCS version you are using? 

> Username is showing as root on welcome email

Both issues seems to be misconfiguration on your part or unsupported version. Also, login to panel feature is already present for both client and admin.

**Comment by mtdas99** [comment]
WHMCS version is 8.0.3 which is the latest version. Login to panel for admin is available under WHMCS but for client it's not showing in the client area.

Moreover is there any possible solution for the above error?

**Comment by mtdas99** [comment]
Can you please help me to show 'use only letters & numbers' in root password field under server configuration form on order page?
Which file could be edited to show this?

**Comment by mtdas99** [comment]
Issue Solved. This was an installation issue. Reinstalled WHMCS and working fine.

Please help me to show 'use only letters & numbers' in root password field under server configuration form on order page.

**Comment by jetchirag** [comment]
That's template issue.
