### ISSUE TITLE
Does this module still work as of 8.1.3? Is there documentation?

### ISSUE THREAD

**Issue by blue928** [jetchirag/cyberpanel-whmcs#4]
I followed the instructions on this project's github page and successfully installed it per the instructions. In whcms when I look at the CyberPanel server and click "test connection" the connection works fine. I can also see in the module log the API request as well as the successful API response of 1 to verify connection.

But when a user goes to create an account on the server, nothing happens. In the module log, there are 0 entries.

Under "Common Errors" none of these are issues.

Where are "Common Errors" supposed to show up? I don't have any errors whatsoever in WHMCS or on the server.

Is there more in dept documentation? This module is almost a year old and a lot has changed. Has it been tested recently to make sure it still works?

Thank you.

**Comment by jetchirag** [comment]
Sorry for delay in getting back. Last manual test was performed 3 months ago but I have not received any bug report on upgrades so I am currently assuming it doesn't break on upgrades to latest versions.

It's also not common for it to not return anything if test connection works fine. I'd also suggest checking your php and webserver logs. Next, open browser's developer console and see what status code and response WHMCS gives upon clicking Create.
