### ISSUE TITLE
How to shown "domain name" input form in client area ?

### ISSUE THREAD

**Issue by henryudha** [jetchirag/cyberpanel-whmcs#5]
Hi @jetchirag ,

thanks for providing this awesome module.

we are integrating whmcs 8.1 with cyberpanel 2.1.
connection between cyberpanel & whmcs, module create, terminate are working well.

question is, on the client side we didnt see any domain form to input customer domain name.
so we need to input domain name manualy from whmcs admin page.

could you give us suggestion how to make customer able to input the domain name in client area ?

thanks and looking forward for your info :)

**Comment by jetchirag** [comment]
In product settings, make sure that "Require Domain" option is ticked. And in General Settings > Domains, atleast one of three Domain Registration options should be ticked as well.
