### ISSUE TITLE
Billing Feature

### ISSUE THREAD

**Issue by vpsinghbaghel** [jetchirag/cyberpanel-whmcs#6]
Hi Chirag,

Why the billing feature has not been included in this cyberpanel-whmcs module?
Is it not done intentionally or there is Work-In-Progress?

Best Regards.
Ved

**Comment by jetchirag** [comment]
It's a provisioning module, billing is handled by WHMCS itself.

**Comment by vpsinghbaghel** [comment]
Hi @jetchirag 
Thank you for responding.
As the title says CyberPanel-WHMCS. I thought it should be providing whmcs features for CyberPanel.
There is no WHMCS available for CyberPanel.
So, is there any work-in-progress for integrating billing part also or any future plans?

Best Regards.
Ved.

**Comment by jetchirag** [comment]
I'm not sure what you mean. It does provide cyberpanel features. WHMCS does handle the billing. This module allows you to configure cyberpanel as server in WHMCS, like cPanel. Please read about role of WHMCS and its Provisioning Modules.

Also, currently there's no new feature work-in-progress for this. It's a complete module for what it does, only maintenance work is being performed.
